dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  dbCreate: update
  username: root
  password: root

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: "jdbc:mysql://localhost:8889/file_uploads?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
